* fantableous
fantableous is a markdown style table editor, generator, and spreadsheet engine written in lua and using treesitter. It is designed to be used alongside the neovim plugin 'nvim-orgmode/orgmode', or as a standalone tool.

Until this plugin reaches feature parity with 'dhruvasagar/vim-table-mode' it is recommended to have that plugin installed as well.
Conflicting keybinds should not matter since each feature provided is an atomic operation for each plugin. Otherwise you may want to ensure that this plugin is loaded second of the two, so that its keybinds take precedence.

** Installation

- Neovim 0.10.0 or later

** Installation

Use your favorite plugin manager:

#+HTML:<details open><summary><b><a href-"https://github.com/folke/lazy.nvim">lazy.nvim<//a></b></summary</br>

#+BEGIN_SRC lua
{
 'qaptoR-nvim/fantableous',
}
#+END_SRC

#+HTML:</det*ls>


** Setup

** Usage
*** Creating a Table on the Fly
todo


*** Moving Around
todo


*** Manipulating Tables
**** Move Cell Up
in progress

**** Move Cell Down
in progress

**** Move Cell Left
in progress

**** Move Cell Right
in progress

**** Delete Row
todo

**** Delete Column
todo

**** Insert Row Above
todo

**** Insert Row Below
todo

**** Insert Column Before
todo

**** Insert Column After
todo


*** Highlight Rows, Cells Based on Content
todo

** Advanced Usage
*** Table Formulas
todo

*** Formula Expressions 
todo

